kind: pipeline
name: test-on-amd64

platform:
  arch: amd64

steps:
- name: test
  image: rust:1.30
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all

---
kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: rust:1.30
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all
